#pragma once

#define DISTANCE_BETWEEN_BALLOON_AND_THE_PATH 20
#define PATH_MOVING_SPEED 3
#define THRESHOLD_MOVING_DISTANCE 260
#define COLLISION_OFFSET_RADIUS 5

#define TIME_RUNNING_STAGE_2 15
#define TIME_RUNNING_STAGE_2_EXTRA 3
#define TIME_RUNNING_STAGE_4 15
#define TIME_RUNNING_STAGE_4_EXTRA 3
#define TIME_RUNNING_STAGE_5 20
#define TIME_RUNNING_STAGE_6 3
#define TIME_RUNNING_STAGE_7_PER_TURN 0.5
#define TIME_RUNNING_STAGE_7 20