#pragma once

#define SCENE_TRANSITION_TIME 2
#define SCENE_OPENING_DELAY_TIME 2

#define TIME_DELAY_BEFORE_OPENING_PANELS 2

#define DISTANCE_BETWEEN_BUTTONS_MENU_SCENE 100
#define NUMBER_OF_ANIMATION_FRAMES_INTRO 20
#define SPRITES_MAX_OPACITY 255
#define ANIMATION_TIME_FOR_ONE_CHANGE 1.5

#define LEVEL_BUTTONS_PATH_MAX_CHARS 100
#define LEVELS_SCROLLVIEW_HEIGHT 500
#define LEVEL_BUTTONS_WIDTH 400
#define LEVEL_NAME_FONT_SIZE 30
#define LEVEL_DESCRIPTION_FONT_SIZE 25
#define NUMBER_OF_LEVELS 9
#define GO_BACK_BUTTON_OFFSET_BOTTOM_SCREEN 30
#define LEVELS_SCROLL_VIEW_OFFSET_CENTER_SCREEN 50
#define GAMEOVER_TITLE_OFFSET_SCREEN_TOP 100
#define DISTANCE_BETWEEN_GAMEOVER_BUTTONS 20