#pragma once

#define CIRCLE_LINE_RADIUS 75
#define BALL_MOVING_SPEED 3 
#define BALLOON_COLLISION_OFFSET_RADIUS 3

#define SPRITES_FADING_OUT_TIME_DURATION 1  
#define NUMBER_OF_INTIAL_DESTROYERS_PER_TYPE 30

#define POSITION_DESTROYERS_OFFSET 100 
#define NUMBER_OF_DESTROYING_WEAPONS_EACH_TYPE 10 

#define BULLET_POSITION_OFFSET_NORMALIZE 20
#define ARROW_POSITION_OFFSET_NORMALIZE 15
#define MISSLE_POSITION_OFFSET_NORMALIZE 14

#define BULLET_TRAVELING_TIME_DURATION_MULTIPLIER 4000
#define ARROW_TRAVELING_TIME_DURATION_MULTIPLIER 3800
#define MISSLE_TRAVELING_TIME_DURATION_MULTIPLIER 3700

#define BULLET_TRAVELING_PATH_NORMALIZE 2000
#define ARROW_TRAVELING_PATH_NORMALIZE 2000
#define MISSLE_TRAVELING_PATH_NORMALIZE 2000

#define DESTROYERS_MOVING_PATH_SLIDING_TIME_DURATION 5

#define DESTROYERS_SPAWNING_STAGE_1_FRAME_COUNT 90
#define DESTROYERS_SPAWNING_STAGE_2_FRAME_COUNT 85
#define DESTROYERS_SPAWNING_STAGE_3_FRAME_COUNT 85

#define FRAME_COUNT_MULTIPLIER 0.1 

#define TIME_RUNNING_STAGE_1 20
#define TIME_RUNNING_STAGE_2 25
#define TIME_RUNNING_STAGE_3 30
#define TIME_RUNNING_STAGE_IDLE 3

#define NUMBER_OF_BOW_ARCHER_FRAMES 19